spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
        namespace:
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: e56ea1fd-a2f8-47de-b84f-737ecc1a5e1d
    data-id: nacos-classify
    group: DEFAULT_GROUP
    auto-refresh: true
    type: yaml
    bootstrap:
      enable: true
    username: nacos
    password: nacos
    file-extension: yaml
