spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8849,127.0.0.1:8859
      discovery:
        server-addr: 127.0.0.1:8849,127.0.0.1:8859
        namespace:
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
nacos:
  config:
    server-addr: 127.0.0.1:8849,127.0.0.1:8859
    namespace:
    data-id: nacos-config-cluster
    group: DEFAULT_GROUP
    auto-refresh: true
    type: yaml
    bootstrap:
      enable: true
    username: nacos
    password: nacos
    file-extension: yaml
