spring:
  application:
    name: nacos-config
  cloud:
    nacos:
      server-addr: 172.18.26.26:8848
      discovery:
        server-addr: 172.18.26.26:8848
        namespace:
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
      config:
        server-addr: 172.18.26.26:8848
        namespace:
        data-id: nacos-config.yaml
        group: DEFAULT_GROUP
        auto-refresh: true
        type: yaml
        bootstrap:
          enable: true
        username: nacos
        password: nacos
        file-extension: yaml

hex:
  tools:
    db:
      url: ${spring.datasource.druid.url}
      type: ${jdbc.type}
      user: ${spring.datasource.druid.username}
      password: ${spring.datasource.druid.password}